import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className="text-4xl text-red-500 underline font-bold">
            Hello world!
          </h1>
          <button className="btn btn-primary">Test</button>
        </main>

        {/* <div id='menus'>
          <Link href={'/'}>
            <h4>Home</h4>
          </Link>
          <Link href={'/news'}>
            <h4>News</h4>
          </Link>
          <Link href={'/blogs'}>
            <h4>Blog</h4>
          </Link>
          <Link href={'/comments'}>
            <h4>Comment</h4>
          </Link>
          <Link href={'/users'}>
            <h4>User</h4>
          </Link>
        </div> */}
      </div>
    </>
  )
}
