import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import NavbarLists from './component/NavbarLists'
import CarouselHome from './component/CarouselHome'

export default function Home() {
  return (
    <>
      <NavbarLists />
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Hi, <a href={'/'}>Selamat Belajar</a>
          </h1>
        </main>

        {/* <div id='menus'>
          <Link href={'/'}>
            <h4>Home</h4>
          </Link>
          <Link href={'/news'}>
            <h4>News</h4>
          </Link>
          <Link href={'/blogs'}>
            <h4>Blog</h4>
          </Link>
          <Link href={'/comments'}>
            <h4>Comment</h4>
          </Link>
          <Link href={'/users'}>
            <h4>User</h4>
          </Link>
        </div> */}
      </div>
    </>
  )
}
